# ============================================================================
# CLOUDFLARE PAGES CONFIGURATION - KAFKASDER MANAGEMENT SYSTEM
# ============================================================================
# Documentation: https://developers.cloudflare.com/pages/

name = "kafkasderpanel"
compatibility_date = "2024-01-01"

# Assets configuration for static site deployment
[assets]
directory = "./dist"

# Production environment
[env.production]
name = "kafkasder-panel-prod"

# Staging environment
[env.staging]
name = "kafkasder-panel-staging"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# NOTE: Environment variables for Vite must be set in Cloudflare Pages Dashboard
# Settings > Environment variables > Production environment
# Required variables:
#   - VITE_SUPABASE_URL
#   - VITE_SUPABASE_ANON_KEY
#   - VITE_APP_NAME
#   - VITE_APP_VERSION
#   - NODE_VERSION (set to "20")

# Custom headers for security and caching
[[pages.headers]]
for = "/assets/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[pages.headers]]
for = "/assets/js/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/assets/css/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/index.html"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# PWA files
[[pages.headers]]
for = "/manifest.webmanifest"
[pages.headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "application/manifest+json"

[[pages.headers]]
for = "/sw.js"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Service-Worker-Allowed = "/"

# Security headers
[[pages.headers]]
for = "/*"
[pages.headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"

# Redirects for SPA routing
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200
