# ============================================================================
# CLOUDFLARE PAGES CONFIGURATION - KAFKASDER MANAGEMENT SYSTEM
# ============================================================================
# Documentation: https://developers.cloudflare.com/pages/

name = "kafkasder-panel"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "kafkasder-panel-prod"

# Staging environment
[env.staging]
name = "kafkasder-panel-staging"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Output directory
[build.upload]
format = "directory"
dir = "dist"

# Pages configuration (required for Cloudflare Pages)
pages_build_output_dir = "dist"

# Environment variables for development
# NOTE: For production, set these in Cloudflare Pages dashboard
# Settings > Environment variables
[vars]
VITE_SUPABASE_URL = "https://gyburnfaszhxcxdnwogj.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5YnVybmZhc3poeGN4ZG53b2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODI2ODMsImV4cCI6MjA3MzQ1ODY4M30.R-AD4ABGXGI1v_VoVqeRDVs9Wio-GJ0HUVRrP0iGG4k"
VITE_APP_NAME = "Kafkasder Management System"
VITE_APP_VERSION = "1.0.0"

# Custom headers for security and caching
[[pages.headers]]
for = "/assets/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"
X-Content-Type-Options = "nosniff"

[[pages.headers]]
for = "/assets/js/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/assets/css/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/index.html"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# PWA files
[[pages.headers]]
for = "/manifest.webmanifest"
[pages.headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "application/manifest+json"

[[pages.headers]]
for = "/sw.js"
[pages.headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Service-Worker-Allowed = "/"

# Security headers
[[pages.headers]]
for = "/*"
[pages.headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"

# Redirects for SPA routing
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200
