name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME || 'Kafkasder Management System' }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION || '1.0.0' }}
          VITE_APP_DEBUG: "false"
          VITE_ENABLE_MOCK_DATA: "false"
          VITE_ENABLE_OCR: "true"
          VITE_ENABLE_PWA: "true"
          VITE_ENABLE_ANALYTICS: "true"
          VITE_ENABLE_OFFLINE_MODE: "true"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kafkasderpanel
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
